version:                "3"
services:
  smartbrains_node:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./app:/home/node/app
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      ports:
        - 3000:3000
      container_name: smartbrains_node
